version: "3"
services: 
  mysql_db: 
    container_name: mysql_container
    environment: 
      MYSQL_DATABASE: wordpresstest
      MYSQL_PASSWORD: bhautik17
      MYSQL_ROOT_PASSWORD: bhautik@2022
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD:
    image: "mysql:5.7"
    restart: always
    volumes: 
      - "mysql:/var/lib/mysql"
  wordpress: 
    container_name: wordpress_container
    depends_on: 
      - mysql_db
    environment: 
      WORDPRESS_DB_HOST: "mysql_db:3306"
      WORDPRESS_DB_NAME: wordpresstest
      WORDPRESS_DB_PASSWORD: bhautik@2022
      WORDPRESS_DB_USER: root
    image: "wordpress:latest"
    ports: 
      - "8001:80"
    restart: always
    volumes: 
      - "./wordpress:/var/www/html"
volumes: 
  mysql: {}